//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAIL_INVOICE
    {
        public int id_detail { get; set; }
        public int id_invoice { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<int> id_product { get; set; }
    
        public virtual INVOICE INVOICE { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
